"""empty message

Revision ID: 2123f055b6d3
Revises: 
Create Date: 2023-07-21 14:47:35.311424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2123f055b6d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_info', sa.Column('is_key_founded', sa.Boolean(), nullable=True))
    op.add_column('domain_info', sa.Column('extra_info', sa.JSON(), nullable=True))
    op.drop_column('domain_info', 'is_founded')
    op.add_column('test', sa.Column('extra_info', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'extra_info')
    op.add_column('domain_info', sa.Column('is_founded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('domain_info', 'extra_info')
    op.drop_column('domain_info', 'is_key_founded')
    # ### end Alembic commands ###
