"""empty message

Revision ID: b96b453a6c55
Revises: 2123f055b6d3
Create Date: 2023-07-31 11:05:12.443627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96b453a6c55'
down_revision = '2123f055b6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.add_column('domain_info', sa.Column('is_it_key', sa.Boolean(), nullable=True))
    op.drop_column('domain_info', 'is_key_founded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_info', sa.Column('is_key_founded', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('domain_info', 'is_it_key')
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('extra_info', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
